
#Основные настройки VoidMode
[general]
	#Включить режим небытия при входе на сервер.
	enableVoidMode = true
	#Задержка в тиках перед выполнением команд после входа на сервер.
	#20 тиков = 1 секунда. Рекомендуется 20-40 для стабильной работы FancyMenu.
	#Range: 0 ~ 400
	commandDelayTicks = 20

#Настройки команд
[commands]
	#Список команд, выполняемых при входе на сервер.
	#НЕ добавляйте '/' в начало команды.
	#Доступная переменная: {player} — будет заменена на ник игрока.
	onJoin = ["openguiscreen maps"]
	#Вайт-лист команд, разрешённых к вводу через чат в режиме небытия.
	#НЕ добавляйте '/' в начало.
	#Пример: ["voidmode off", "spawn", "hub"]
	allowedChatCommands = ["voidmode off", "spawn", "hub"]

